module.exports.announcements = require('./announcements')
module.exports.comments = require('./comments')
module.exports.events = require('./events')
module.exports.volunteers = require('./volunteers')
module.exports.communities = require('./community')